package org.bc.common.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * www.rmworking.com/blog
 * Table: r_user
 do_not_delete_during_merge 2018-04-24 11:22:18
 */
public class User implements Serializable {
    /**
     * <pre>
     * 
     * 表字段 : r_user.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 用户登录id
     * 表字段 : r_user.logonid
     * </pre>
     * 
     */
    private String logonid;

    /**
     * <pre>
     * 用户登录口令
     * 表字段 : r_user.logon_pwd
     * </pre>
     * 
     */
    private String logonPwd;

    /**
     * <pre>
     * 姓名
     * 表字段 : r_user.name
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 性别:0女1男
     * 表字段 : r_user.gender
     * </pre>
     * 
     */
    private Integer gender;

    /**
     * <pre>
     * 工号
     * 表字段 : r_user.workno
     * </pre>
     * 
     */
    private String workno;

    /**
     * <pre>
     * 身份证号
     * 表字段 : r_user.idno
     * </pre>
     * 
     */
    private String idno;

    /**
     * <pre>
     * 手机号
     * 表字段 : r_user.mobile
     * </pre>
     * 
     */
    private String mobile;

    /**
     * <pre>
     * 可用状态：0启用，1禁用
     * 表字段 : r_user.status
     * </pre>
     * 
     */
    private Integer status;

    /**
     * <pre>
     * 用户隶属组织
     * 表字段 : r_user.org_id
     * </pre>
     * 
     */
    private Integer orgId;

    /**
     * <pre>
     * 创建人
     * 表字段 : r_user.created_by
     * </pre>
     * 
     */
    private Integer createdBy;

    /**
     * <pre>
     * 更新人
     * 表字段 : r_user.updated_by
     * </pre>
     * 
     */
    private Integer updatedBy;

    /**
     * <pre>
     * 创建日期
     * 表字段 : r_user.created_on
     * </pre>
     * 
     */
    private Date createdOn;

    /**
     * <pre>
     * 更新日期
     * 表字段 : r_user.updated_on
     * </pre>
     * 
     */
    private Date updatedOn;

    /**
     * <pre>
     * ehr employee id
     * 表字段 : r_user.ehr_user_id
     * </pre>
     * 
     */
    private String ehrUserId;

    private String updatedNo;
    private String createdNo;
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_user
     2018-04-24 11:22:18
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLogonid() {
        return logonid;
    }

    public void setLogonid(String logonid) {
        this.logonid = logonid == null ? null : logonid.trim();
    }

    public String getLogonPwd() {
        return logonPwd;
    }

    public void setLogonPwd(String logonPwd) {
        this.logonPwd = logonPwd == null ? null : logonPwd.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getWorkno() {
        return workno;
    }

    public void setWorkno(String workno) {
        this.workno = workno == null ? null : workno.trim();
    }

    public String getIdno() {
        return idno;
    }

    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public String getEhrUserId() {
        return ehrUserId;
    }

    public void setEhrUserId(String ehrUserId) {
        this.ehrUserId = ehrUserId == null ? null : ehrUserId.trim();
    }

    public String getUpdatedNo() {
        return updatedNo;
    }

    public void setUpdatedNo(String updatedNo) {
        this.updatedNo = updatedNo;
    }

    public String getCreatedNo() {
        return createdNo;
    }

    public void setCreatedNo(String createdNo) {
        this.createdNo = createdNo;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", logonid='" + logonid + '\'' +
                ", logonPwd='" + logonPwd + '\'' +
                ", name='" + name + '\'' +
                ", gender=" + gender +
                ", workno='" + workno + '\'' +
                ", idno='" + idno + '\'' +
                ", mobile='" + mobile + '\'' +
                ", status=" + status +
                ", orgId=" + orgId +
                ", createdBy=" + createdBy +
                ", updatedBy=" + updatedBy +
                ", createdOn=" + createdOn +
                ", updatedOn=" + updatedOn +
                ", ehrUserId='" + ehrUserId + '\'' +
                ", updatedNo='" + updatedNo + '\'' +
                ", createdNo='" + createdNo + '\'' +
                ", orgName='" + orgName + '\'' +
                '}';
    }
}