package org.bc.common.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * www.rmworking.com/blog
 * Table: r_user_org_permission
 do_not_delete_during_merge 2018-04-24 11:22:18
 */
public class UserOrgPermission implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : r_user_org_permission.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 状态
     * 表字段 : r_user_org_permission.status
     * </pre>
     * 
     */
    private Integer status;

    /**
     * <pre>
     * 角色所属组织表达式
     * 表字段 : r_user_org_permission.express
     * </pre>
     * 
     */
    private String express;

    /**
     * <pre>
     * 创建人
     * 表字段 : r_user_org_permission.created_by
     * </pre>
     * 
     */
    private Integer createdBy;

    /**
     * <pre>
     * 更新人
     * 表字段 : r_user_org_permission.updated_by
     * </pre>
     * 
     */
    private Integer updatedBy;

    /**
     * <pre>
     * 创建日期
     * 表字段 : r_user_org_permission.created_on
     * </pre>
     * 
     */
    private Date createdOn;

    /**
     * <pre>
     * 更新日期
     * 表字段 : r_user_org_permission.updated_on
     * </pre>
     * 
     */
    private Date updatedOn;

    /**
     * <pre>
     * 
     * 表字段 : r_user_org_permission.org_id
     * </pre>
     * 
     */
    private Integer orgId;

    /**
     * <pre>
     * ehr用户 code
     * 表字段 : r_user_org_permission.user_id
     * </pre>
     * 
     */
    private Integer userId;

    private String createdNo;
    private Integer enEdit;
    private  Integer orgEnEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_user_org_permission
     2018-04-24 11:22:18
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getExpress() {
        return express;
    }

    public void setExpress(String express) {
        this.express = express == null ? null : express.trim();
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getCreatedNo() {
        return createdNo;
    }

    public void setCreatedNo(String createdNo) {
        this.createdNo = createdNo;
    }

    public Integer getEnEdit() {
        return enEdit;
    }

    public void setEnEdit(Integer enEdit) {
        this.enEdit = enEdit;
    }

    public Integer getOrgEnEdit() {
        return orgEnEdit;
    }

    public void setOrgEnEdit(Integer orgEnEdit) {
        this.orgEnEdit = orgEnEdit;
    }
}