package org.bc.common.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * www.rmworking.com/blog
 * Table: r_user_org_role
 do_not_delete_during_merge 2018-04-24 11:22:18
 */
public class UserOrgRole implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : r_user_org_role.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 开始时间
     * 表字段 : r_user_org_role.start_on
     * </pre>
     * 
     */
    private Date startOn;

    /**
     * <pre>
     * 结束时间
     * 表字段 : r_user_org_role.end_on
     * </pre>
     * 
     */
    private Date endOn;

    /**
     * <pre>
     * 创建人
     * 表字段 : r_user_org_role.created_by
     * </pre>
     * 
     */
    private Integer createdBy;

    /**
     * <pre>
     * 更新人
     * 表字段 : r_user_org_role.updated_by
     * </pre>
     * 
     */
    private Integer updatedBy;

    /**
     * <pre>
     * 创建日期
     * 表字段 : r_user_org_role.created_on
     * </pre>
     * 
     */
    private Date createdOn;

    /**
     * <pre>
     * 更新日期
     * 表字段 : r_user_org_role.updated_on
     * </pre>
     * 
     */
    private Date updatedOn;

    /**
     * <pre>
     * 角色id
     * 表字段 : r_user_org_role.role_id
     * </pre>
     * 
     */
    private Integer roleId;

    /**
     * <pre>
     * 用户组织权限id
     * 表字段 : r_user_org_role.user_org_perm_id
     * </pre>
     * 
     */
    private Integer userOrgPermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_user_org_role
     2018-04-24 11:22:18
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStartOn() {
        return startOn;
    }

    public void setStartOn(Date startOn) {
        this.startOn = startOn;
    }

    public Date getEndOn() {
        return endOn;
    }

    public void setEndOn(Date endOn) {
        this.endOn = endOn;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getUserOrgPermId() {
        return userOrgPermId;
    }

    public void setUserOrgPermId(Integer userOrgPermId) {
        this.userOrgPermId = userOrgPermId;
    }
}