package org.bc.mq.persistence.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * www.rmworking.com/blog
 * Table: c_org_hosp
 do_not_delete_during_merge 2018-04-24 13:53:25
 */
public class OrgHosp implements Serializable {
    /**
     * <pre>
     * 主键
     * 表字段 : c_org_hosp.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 名称
     * 表字段 : c_org_hosp.name
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 区域编码
     * 表字段 : c_org_hosp.area_code
     * </pre>
     * 
     */
    private Integer areaCode;

    /**
     * <pre>
     * 组织级别
     * 表字段 : c_org_hosp.level
     * </pre>
     * 
     */
    private Integer level;

    /**
     * <pre>
     * 创建人
     * 表字段 : c_org_hosp.created_by
     * </pre>
     * 
     */
    private Integer createdBy;

    /**
     * <pre>
     * 更新人
     * 表字段 : c_org_hosp.updated_by
     * </pre>
     * 
     */
    private Integer updatedBy;

    /**
     * <pre>
     * 创建日期
     * 表字段 : c_org_hosp.created_on
     * </pre>
     * 
     */
    private Date createdOn;

    /**
     * <pre>
     * 更新日期
     * 表字段 : c_org_hosp.updated_on
     * </pre>
     * 
     */
    private Date updatedOn;

    /**
     * <pre>
     * 父组织id
     * 表字段 : c_org_hosp.org_id
     * </pre>
     * 
     */
    private Integer orgId;
    /**
     * <pre>
     * 可用状态：0启用，1禁用
     * 表字段 : c_hosp_room.status
     * </pre>
     *
     */
    private Integer status;

    /**
     * 别名
     */
    private String byName;

    /**
     * 企业CODE
     */
    private String unitCode;

    public String getByName() {
        return byName;
    }

    public void setByName(String byName) {
        this.byName = byName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_org_hosp
     2018-04-24 13:53:25
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(Integer areaCode) {
        this.areaCode = areaCode;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }
}