package org.bc.saas.persistence.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * www.rmworking.com/blog
 * Table: c_advice
 do_not_delete_during_merge 2018-06-20 18:31:13
 */
public class Advice implements Serializable {
    /**
     * <pre>
     * id
     * 表字段 : c_advice.id
     * </pre>
     * 
     */
    private Long id;

    /**
     * <pre>
     * 编码
     * 表字段 : c_advice.code
     * </pre>
     * 
     */
    private String code;

    /**
     * <pre>
     * 拼音
     * 表字段 : c_advice.py
     * </pre>
     * 
     */
    private String py;

    /**
     * <pre>
     * 名称
     * 表字段 : c_advice.name
     * </pre>
     * 
     */
    private String name;

    /**
     * <pre>
     * 显示顺序
     * 表字段 : c_advice.idx
     * </pre>
     * 
     */
    private Integer idx;

    /**
     * <pre>
     * 建议内容
     * 表字段 : c_advice.description
     * </pre>
     * 
     */
    private String description;

    /**
     * <pre>
     * 部门类别id
     * 表字段 : c_advice.dept_type_id
     * </pre>
     * 
     */
    private Integer deptTypeId;

    /**
     * <pre>
     * 操作说明
     * 表字段 : c_advice.operate_desc
     * </pre>
     * 
     */
    private String operateDesc;

    /**
     * <pre>
     * 出处
     * 表字段 : c_advice.provenance
     * </pre>
     * 
     */
    private String provenance;

    /**
     * <pre>
     * 是否为限制项目：0为不是，1为是
     * 表字段 : c_advice.limit_type
     * </pre>
     * 
     */
    private Integer limitType;

    /**
     * <pre>
     * 名词解释
     * 表字段 : c_advice.explain_desc
     * </pre>
     * 
     */
    private String explainDesc;

    /**
     * <pre>
     * 报表中是否需要展示该名词解释 0为否，1为是
     * 表字段 : c_advice.is_infomation_explain
     * </pre>
     * 
     */
    private Integer isInfomationExplain;

    /**
     * <pre>
     * 是否具有健康危害和解决方案:0为否，1为是
     * 表字段 : c_advice.is_health_hazard_solution
     * </pre>
     * 
     */
    private Integer isHealthHazardSolution;

    /**
     * <pre>
     * 健康危害
     * 表字段 : c_advice.health_hazard
     * </pre>
     * 
     */
    private String healthHazard;

    /**
     * <pre>
     * 解决方案
     * 表字段 : c_advice.solution
     * </pre>
     * 
     */
    private String solution;

    /**
     * <pre>
     * 状态
     * 表字段 : c_advice.status
     * </pre>
     * 
     */
    private Integer status;

    /**
     * <pre>
     * 操作者
     * 表字段 : c_advice.updated_by
     * </pre>
     * 
     */
    private Integer updatedBy;

    /**
     * <pre>
     * 操作时间
     * 表字段 : c_advice.updated_on
     * </pre>
     * 
     */
    private Date updatedOn;

    /**
     * <pre>
     * 操作ip
     * 表字段 : c_advice.ip_address
     * </pre>
     * 
     */
    private String ipAddress;

    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_advice
     2018-06-20 18:31:13
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getPy() {
        return py;
    }

    public void setPy(String py) {
        this.py = py == null ? null : py.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getIdx() {
        return idx;
    }

    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public Integer getDeptTypeId() {
        return deptTypeId;
    }

    public void setDeptTypeId(Integer deptTypeId) {
        this.deptTypeId = deptTypeId;
    }

    public String getOperateDesc() {
        return operateDesc;
    }

    public void setOperateDesc(String operateDesc) {
        this.operateDesc = operateDesc == null ? null : operateDesc.trim();
    }

    public String getProvenance() {
        return provenance;
    }

    public void setProvenance(String provenance) {
        this.provenance = provenance == null ? null : provenance.trim();
    }

    public Integer getLimitType() {
        return limitType;
    }

    public void setLimitType(Integer limitType) {
        this.limitType = limitType;
    }

    public String getExplainDesc() {
        return explainDesc;
    }

    public void setExplainDesc(String explainDesc) {
        this.explainDesc = explainDesc == null ? null : explainDesc.trim();
    }

    public Integer getIsInfomationExplain() {
        return isInfomationExplain;
    }

    public void setIsInfomationExplain(Integer isInfomationExplain) {
        this.isInfomationExplain = isInfomationExplain;
    }

    public Integer getIsHealthHazardSolution() {
        return isHealthHazardSolution;
    }

    public void setIsHealthHazardSolution(Integer isHealthHazardSolution) {
        this.isHealthHazardSolution = isHealthHazardSolution;
    }

    public String getHealthHazard() {
        return healthHazard;
    }

    public void setHealthHazard(String healthHazard) {
        this.healthHazard = healthHazard == null ? null : healthHazard.trim();
    }

    public String getSolution() {
        return solution;
    }

    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }
}